users:
  folkcertReadOnly:
    token: replaceMe
    resources:
      artist: ['GET']
      concert: ['GET']
      search: ['GET']
  folkcertReadWrite:
    token: replaceMe
    resources:
      artist: ['GET', 'POST', 'PUT', 'DELETE']
      concert: ['GET', 'POST', 'PUT', 'DELETE']
      search: ['GET', 'POST', 'PUT', 'DELETE']
      linkType: ['GET', 'POST', 'PUT', 'DELETE']
      genre: ['GET', 'POST', 'PUT', 'DELETE']