users:
  folkcertReadOnly:
    token: replaceMe
    resources:
      artist: ['GET', 'OPTIONS']
      concert: ['GET', 'OPTIONS']
      search: ['GET', 'OPTIONS']
  folkcertReadWrite:
    token: replaceMe
    resources:
      artist: ['GET', 'POST', 'PUT', 'DELETE', 'OPTIONS']
      concert: ['GET', 'POST', 'PUT', 'DELETE', 'OPTIONS']
      search: ['GET', 'POST', 'PUT', 'DELETE', 'OPTIONS']
      linkType: ['GET', 'POST', 'PUT', 'DELETE', 'OPTIONS']
      genre: ['GET', 'POST', 'PUT', 'DELETE', 'OPTIONS']