<?php

namespace AppBundle\Repository;

/**
 * ConcertRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ConcertRepository extends \Doctrine\ORM\EntityRepository
{
    public function getAll($filters)
    {
        $qb = $this->createQueryBuilder('c')
            ->where('c.active = true');

        if (!empty($filters['artist'])) {
            $qb->andWhere(
                $qb->expr()->eq('c.artist', ':artist')
            )
            ->setParameter('artist', $filters['artist']);
        }

        if (!empty($filters['genre'])) {
            $qb->andWhere(
                $qb->expr()->eq('c.genre', ':genre')
            )
            ->setParameter('genre', $filters['genre']);
        }

        return $qb
            ->getQuery()
            ->getResult();
    }
}
