<?php

namespace AppBundle\Repository;

/**
 * LinkTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LinkTypeRepository extends \Doctrine\ORM\EntityRepository
{
}
